/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWhatsappRouteImport } from './routes/api/whatsapp'
import { Route as ApiTelegramRouteImport } from './routes/api/telegram'
import { Route as ApiSendReminderRouteImport } from './routes/api/send-reminder'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiPublicHooksTickRemindersRouteImport } from './routes/api/public/hooks/tick-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappRoute = ApiWhatsappRouteImport.update({
  id: '/api/whatsapp',
  path: '/api/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTelegramRoute = ApiTelegramRouteImport.update({
  id: '/api/telegram',
  path: '/api/telegram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendReminderRoute = ApiSendReminderRouteImport.update({
  id: '/api/send-reminder',
  path: '/api/send-reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTickRemindersRoute =
  ApiPublicHooksTickRemindersRouteImport.update({
    id: '/api/public/hooks/tick-reminders',
    path: '/api/public/hooks/tick-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/send-reminder': typeof ApiSendReminderRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/public/hooks/tick-reminders': typeof ApiPublicHooksTickRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/send-reminder': typeof ApiSendReminderRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/public/hooks/tick-reminders': typeof ApiPublicHooksTickRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/send-reminder': typeof ApiSendReminderRoute
  '/api/telegram': typeof ApiTelegramRoute
  '/api/whatsapp': typeof ApiWhatsappRoute
  '/api/public/hooks/tick-reminders': typeof ApiPublicHooksTickRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/chat'
    | '/api/send-reminder'
    | '/api/telegram'
    | '/api/whatsapp'
    | '/api/public/hooks/tick-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/chat'
    | '/api/send-reminder'
    | '/api/telegram'
    | '/api/whatsapp'
    | '/api/public/hooks/tick-reminders'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/send-reminder'
    | '/api/telegram'
    | '/api/whatsapp'
    | '/api/public/hooks/tick-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSendReminderRoute: typeof ApiSendReminderRoute
  ApiTelegramRoute: typeof ApiTelegramRoute
  ApiWhatsappRoute: typeof ApiWhatsappRoute
  ApiPublicHooksTickRemindersRoute: typeof ApiPublicHooksTickRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp': {
      id: '/api/whatsapp'
      path: '/api/whatsapp'
      fullPath: '/api/whatsapp'
      preLoaderRoute: typeof ApiWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/telegram': {
      id: '/api/telegram'
      path: '/api/telegram'
      fullPath: '/api/telegram'
      preLoaderRoute: typeof ApiTelegramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-reminder': {
      id: '/api/send-reminder'
      path: '/api/send-reminder'
      fullPath: '/api/send-reminder'
      preLoaderRoute: typeof ApiSendReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/tick-reminders': {
      id: '/api/public/hooks/tick-reminders'
      path: '/api/public/hooks/tick-reminders'
      fullPath: '/api/public/hooks/tick-reminders'
      preLoaderRoute: typeof ApiPublicHooksTickRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSendReminderRoute: ApiSendReminderRoute,
  ApiTelegramRoute: ApiTelegramRoute,
  ApiWhatsappRoute: ApiWhatsappRoute,
  ApiPublicHooksTickRemindersRoute: ApiPublicHooksTickRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
